services:
  - type: web
    name: fitness-tracker-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://fitness-tracker-backend.onrender.com/api
