services:
  - type: web
    name: fitness-tracker-backend
    env: node
    plan: free
    buildCommand: cd ../frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: fitness-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://fitness-tracker-frontend.onrender.com
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: fitness-tracker-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://fitness-tracker-backend.onrender.com/api

databases:
  - name: fitness-tracker-db
    databaseName: fitness-tracker
    user: fitness-tracker-user
